import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layout/Navbar";

const cairo = Cairo({
   subsets: ["latin", "arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${cairo.className} font-cairo antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}